# Generated by Django 3.2.9 on 2022-02-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.IntegerField(default=1, unique=True)),
                ('username', models.CharField(default='NA', max_length=550)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('account_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.account')),
            ],
        ),
    ]
